### PR TITLE
[Refactor] CorruptionEngineForm is now built with more modular controls

### PR DESCRIPTION
**Pull request by scowalt**
Some regression risk here. I did my absolute best to make sure all of the fields and checkboxes and updowns got rewired correctly. However, I had to do much of this manually. There is some risk that I missed something and made a previously-functional checkbox not work anymore.

### CODE REVIEW

**Comment by NarryG** [comment]
I'll take a good look at it for regressions.    

We may be starting to reach the point where we could start looking towards testing. We'll need to figure out a system for either mocking/stubbing out Netcore. I have absolutely no idea how to test a networked program so that's a big task to look into.  
We can build out unit tests for some parts of the codebase, but I feel like we're going to need to lean more on integration tests.
We do have the local router which allows us to bypass the tcp/udp stack and run Netcore messages in-process, but it skips the serialization/deserialization which is a spot where bugs have snuck in in the past so if we use that, we'll need to make a version that runs it through the whole stack. Something to start thinking about.

**Comment by NarryG** [comment]
The controls appear to be failing to design.  

```
Constructor on type 'RTCV.UI.Components.EngineConfig.EngineConfigControl' not found.    
 
 
Instances of this error (1)  
 
1.   Hide Call Stack 
 
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
at System.ComponentModel.Design.DesignSurface.CreateInstance(Type type)
at Microsoft.VisualStudio.Design.VSDesignSurface.CreateInstance(Type type)
at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type componentType, String name)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager manager, CodeTypeDeclaration declaration)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(Int32 fReload)  
```

**Comment by NarryG** [comment]
There appears to be some regression in a few spots. I'll test further but just dropping these here for now.

- Nightmare engine doesn't appear to be respecting the min/max boxes.
- toggleLimiterBoxSource doesn't account for the cluster engine's boxes (this one might not actually be a regression and be a bug that I'm noticing now while testing). This hacky method of attaching/detaching the bindingsource could probably be wrapped up much cleaner than having a method which has to touch all the boxes independently.

**Comment by scowalt** [comment]
I fixed the designer issue. A pull + a solution rebuild is required for the change to work.

**Comment by scowalt** [comment]
> There appears to be some regression in a few spots. I'll test further but just dropping these here for now.
> 
> * Nightmare engine doesn't appear to be respecting the min/max boxes.
> * toggleLimiterBoxSource doesn't account for the cluster engine's boxes (this one might not actually be a regression and be a bug that I'm noticing now while testing). This hacky method of attaching/detaching the bindingsource could probably be wrapped up much cleaner than having a method which has to touch all the boxes independently.

I'm not confident either of these issues are regressions.

No part of the code I could find in `506` appears to be reading the value of `nmMinValueNightmare` or `nmMaxValueNightmare`. Unless there's something I'm missing, these boxes have never been hooked up to anything.

Similarly, the `toggleLimitBoxSource` issue is not a regression. In `506`, we currently only handle `cbLimiterList`, `cbValueList`, `cbVectorLimiterList`, and `cbVectorValueList`. The Cluster Engine's box, `cbClusterLimiterList`, remains untouched.

I can easily tack on the `cbClusterLimiterList` functionality to this change if you want. I don't know enough about the Nightmare engine issue to know how to fix it correctly.

**Comment by NarryG** [comment]
> > There appears to be some regression in a few spots. I'll test further but just dropping these here for now.
> > 
> > * Nightmare engine doesn't appear to be respecting the min/max boxes.
> > * toggleLimiterBoxSource doesn't account for the cluster engine's boxes (this one might not actually be a regression and be a bug that I'm noticing now while testing). This hacky method of attaching/detaching the bindingsource could probably be wrapped up much cleaner than having a method which has to touch all the boxes independently.
> 
> I'm not confident either of these issues are regressions.
> 
> No part of the code I could find in `506` appears to be reading the value of `nmMinValueNightmare` or `nmMaxValueNightmare`. Unless there's something I'm missing, these boxes have never been hooked up to anything.
> 
> Similarly, the `toggleLimitBoxSource` issue is not a regression. In `506`, we currently only handle `cbLimiterList`, `cbValueList`, `cbVectorLimiterList`, and `cbVectorValueList`. The Cluster Engine's box, `cbClusterLimiterList`, remains untouched.
> 
> I can easily tack on the `cbClusterLimiterList` functionality to this change if you want. I don't know enough about the Nightmare engine issue to know how to fix it correctly.

That first one looks like it might have been a regression in another PR then as it was previously used.  https://github.com/redscientistlabs/RTCV/blob/master/Source/Frontend/UI/Components/Engine%20Config/RTC_CorruptionEngine_Form.cs#L433

The second one does look like it has been an issue since the cluster engine was introduced. We could directly rig it up to match the code as it exists and then replace it all with a better solution to keep them synced.

**Comment by scowalt** [comment]
Yep, looks like I accidentally deleted the min/max handlers for the Hellgenie and Nightmare engines in #147 . I'll fix that up

**Comment by scowalt** [comment]
I've now fixed both of the issues you brought up

**Comment by NarryG** [comment]
I haven't run into any other issues so I'll merge this in and if regressions show up, we'll fix them as we go along.

**Pull request merged**
