### PR TITLE
[Cleanup] RTC_SanitizeTool_Form member cleanup

### PR DESCRIPTION
**Pull request by scowalt**
`originalBlastLayer` was made private and renamed

`workBlastLayer` was assigned but never read, so I deleted it.

### CODE REVIEW

**Comment by NarryG** [comment]
@ircluzar You remember the original reasoning behind workBlastLayer? Seems like this might be a bug if you intended to use it for something but never did.

**Comment by NarryG** [comment]
Replying for him since he's on mobile. 

workBlastLayer can be removed. Accidental leftover code that snuck through due to no real code-quality checks on our end (something that might be good to work on at some point once we have all the rules in place)

This one has to go on hold because of the AutoSanitizer plugin. The code for that isn't on Github at the moment (thus you didn't see why it was public), but it hooks into the public nature of this form to drive it automatically. Once everything is properly split into components, we'll be able to build a proper API exposing the functionality we need as we move forward and get rid of bad smells like this.

**Comment by scowalt** [comment]
Got it. I guess I should avoid work on all of the form code until the AutoSanitizer work is finished?

**Comment by NarryG** [comment]
Since you've renamed so much (that'll break the reason to prevent merging this anyways), I see no reason to hold off on this one. We can re-expose the variables we need since we're already going to have to apply a bunch of small fixes to the autosanitizer for the next release.

**Pull request merged**
