### PR TITLE
[Dev] Created BuildAll script

### PR DESCRIPTION
**Pull request by scowalt**
This will build all of the projects that have been checked out and setup locally. Any project that isn't found will be skipped.

This should be helpful for local development

image
image

### CODE REVIEW

**Comment by NarryG** [comment]
Could you swap PCSX2 to build release? Since that's what we actually deploy, this build script should probably reflect that.

**Comment by scowalt** [comment]
Done. I used the configurations that were in CI. I created #218 to update CI if this is what we want to build in CI as well.

The rest will default to "Debug|AnyCPU". Do you want me to change that as well?

**Comment by scowalt** [comment]
Or maybe we should have `-Debug` and `-Release` flags for the build script that change the configuration?

**Comment by NarryG** [comment]
I like that.

**Comment by scowalt** [comment]
Alright, I'll put that in the next iteration 👍

**Comment by scowalt** [comment]
I'm going to set the default to `-Debug` since I assume `-Release` will be used less frequently

**Comment by NarryG** [comment]
When using Visual Studio's cmake, a separate SLN is generated for debug and release mode and the path changes (x64-Debug, x64-Release, x64-RelWithDebInfo). Currently, I've been using VS's cmake for Melon but it might make more sense to use normal cmake since it'll give us a single SLN instead of multiple based on configuration. I'll take a look and see if I have any issues using standalone cmake.

**Comment by scowalt** [comment]
I was originally using standalone cmake for melonDS-vanguard, so I was able to get it to work for me. Let me know if you have any issues.

**Comment by NarryG** [comment]
Standalone cmake is fine, but it does need some path fixes. I'm thinking just the "builld" folder the same as Citra would make sense so it'd be build/melonDS.sln

**Comment by NarryG** [comment]
Scratch that. It seems it's only fine with MSBuild and not VS. 
This command in the cmakefile 
`${CMAKE_COMMAND} -E copy $<TARGET_PROPERTY:libui,BINARY_DIR>/libui.dir/${CMAKE_CONFIGURATION_TYPES}/resources.res ${_LIBUI_STATIC_RES}`

Doesn't work because `CMAKE_CONFIGURATION_TYPES` isn't handled from configuration to configuration. I'll fix the scripts up to use a different method of copying the file.

**Comment by NarryG** [comment]
I've fixed up the build for Melon to work properly with standalone cmake & VS, You'll need to make a few minor tweaks to the script since I changed paths, but otherwise I expect it to work fine since you said it was working fine under MSBuild before.

**Comment by scowalt** [comment]
Path updated. For consistency, I updated this in CI as well.

**Pull request merged**
